version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: m123
      POSTGRES_DB: musicapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: music-app
    container_name: music_app
    ports:
      - "8080:8080"
    depends_on:
      - db

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/musicapp
      SPRING_DATASOURCE_USERNAME: music
      SPRING_DATASOURCE_PASSWORD: m123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: