apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    spring.datasource.url= jdbc:postgresql://db:5432/musicapp
    spring.datasource.username= music
    spring.datasource.password= m123
